include(${CMAKE_HEAD}/compile_all_file.cmake)
include(${CMAKE_HEAD}/link_selected_shared_object.cmake)
macro(compile_execute)
get_source_files_exclude_build(SRC_FILES)
add_executable(${PROJECT_NAME} ${SRC_FILES})
link_so_files(${PROJECT_NAME} "${EXTERN_SHARED_OBJECT}")
target_include_directories(${PROJECT_NAME} PRIVATE ${INCLUDE_DIR})
endmacro()
compile_execute()
