include(${CMAKE_HEAD}/compile_all_file.cmake)
include(${CMAKE_HEAD}/link_selected_shared_object.cmake)
macro(compile_shared_object)
    get_source_files_exclude_build(SRC_FILES)
    set(shared_object_CPP "${PROJECT_NAME}_shared")
    add_library(${shared_object_CPP} SHARED ${SRC_FILES})
    set_target_properties(${shared_object_CPP}  PROPERTIES OUTPUT_NAME ${PROJECT_NAME})
    if(LIBXML2)
        find_package(LibXml2 REQUIRED)
        target_link_libraries(${shared_object_CPP} LibXml2::LibXml2)
    endif()
    link_so_files(${shared_object_CPP} "${EXTERN_SHARED_OBJECT}")
    target_include_directories(${shared_object_CPP} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
    target_include_directories(${shared_object_CPP} PRIVATE ${INCLUDE_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${BIN_DIR})
    install(TARGETS ${shared_object_CPP}  LIBRARY DESTINATION ${BIN_DIR})
endmacro()
compile_shared_object()
